server:
  base-url: ${BASE_URL}

spring:
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop                # ddl 자동 작성 여부
    properties:
      hibernate:
        format_sql: true             # 하이버네이트가 실행한 SQL을 출력할 때 보기 좋게 정렬
        use_sql_comments: true
        show_sql: true               # 하이버네이트가 실행한 SQL을 출력
        jdbc:
          batch_size: 100              #   insert/update 쿼리를 원하는 개수만큼 모아서 DB에 날릴 수 있는 옵션
        default_batch_fetch_size: 100

  datasource:
    driver-class-name: org.postgresql.Driver  # PostgreSQL 드라이버 클래스
    url: ${DB_URL}  # PostgreSQL URL
    username: ${DB_USERNAME}  # PostgreSQL 사용자 이름
    password: ${DB_PASSWORD}  # PostgreSQL 비밀번호

jasypt:
  encryptor:
    key: ${JASYPT_ENCRYPTOR_KEY}